# This is a basic workflow to help you get started with Actions
name: sdk-index 

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2 

    - name: Csp test start
      run: |
        # repo_root=$(pwd) && cd $repo_root/tools 
        # chmod a+x before_install.sh && source before_install.sh
        # sudo apt-get install python3-pip python3-setuptools python3-wheel -y
        # python3 -m pip install wheel jsonschema PyEmail
        # chmod a+x script.sh && source script.sh
        python test2.py
      shell: bash
