# This is a basic workflow to help you get started with Actions
name: sdk-index

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  # runs at 00:00 UTC every day
  schedule:
    - cron:  '0 0 * * *'
  push:
    branches: [ master ]
    paths-ignore:
      - docs/**
      - cmake/**
      - scripts/**
  pull_request:
    branches: [ master ]
    paths-ignore:
      - docs/**
      - cmake/**
      - scripts/**

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@master
      with:
        python-version: 3.8
    - name: Run unit tests
      env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        env
        #docker pull summergift/csp_test:v1.0
        pip install selenium && python actions.py"
